'use strict';

const { getAccessMatrix, saveAccessMatrix } = require('./storage.cjs');

const DEFAULT_ACCESS_MATRIX = [
  {
    roleKey: 'dev_responsavel',
    roleName: 'Dev Responsavel',
    reportsShortage: false,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: true,
    viewsReports: true,
    viewsAuditTrail: true,
    managesUsersAndRoles: true,
    accessesDatabase: 'future_only',
    accessesFinancialSystems: 'future_only',
    notes: 'Admin tecnico do agente. Nao deve comprar nem aprovar por papel operacional.'
  },
  {
    roleKey: 'proprietario',
    roleName: 'Proprietario',
    reportsShortage: false,
    validatesShortage: false,
    requestsQuotes: true,
    respondsToQuotes: false,
    comparesQuotes: true,
    approvesPurchase: true,
    executesPurchase: false,
    receivesOperationalAlerts: true,
    viewsReports: true,
    viewsAuditTrail: true,
    managesUsersAndRoles: true,
    accessesDatabase: 'approval_required',
    accessesFinancialSystems: 'approval_required',
    notes: 'Dono aprova compras criticas e acessos sensiveis.'
  },
  {
    roleKey: 'gerente_geral',
    roleName: 'Gerente Geral',
    reportsShortage: true,
    validatesShortage: true,
    requestsQuotes: true,
    respondsToQuotes: false,
    comparesQuotes: true,
    approvesPurchase: true,
    executesPurchase: false,
    receivesOperationalAlerts: true,
    viewsReports: true,
    viewsAuditTrail: true,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Coordena a operacao e pode aprovar dentro da politica da empresa.'
  },
  {
    roleKey: 'gerente_comercial',
    roleName: 'Gerente Comercial',
    reportsShortage: true,
    validatesShortage: false,
    requestsQuotes: true,
    respondsToQuotes: false,
    comparesQuotes: true,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: true,
    viewsReports: true,
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Influencia prioridade comercial, mas nao compra sozinho por padrao.'
  },
  {
    roleKey: 'secretario',
    roleName: 'Secretario',
    reportsShortage: true,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: true,
    viewsReports: true,
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Faz apoio administrativo e repasses.'
  },
  {
    roleKey: 'balconista',
    roleName: 'Balconista',
    reportsShortage: true,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: false,
    viewsReports: 'limited',
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Reporta falta percebida no atendimento.'
  },
  {
    roleKey: 'caixa',
    roleName: 'Caixa',
    reportsShortage: true,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: false,
    viewsReports: 'limited',
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Sinaliza falta e divergencia operacional sem acesso financeiro sensivel.'
  },
  {
    roleKey: 'gerente_entrega',
    roleName: 'Gerente da Entrega',
    reportsShortage: true,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: true,
    viewsReports: 'limited',
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Recebe impacto logistico de compras e reposicoes.'
  },
  {
    roleKey: 'motorista_entrega',
    roleName: 'Motorista da Entrega',
    reportsShortage: false,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: 'limited',
    viewsReports: false,
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Acesso apenas a atualizacoes da propria rota.'
  },
  {
    roleKey: 'ajudante_entrega',
    roleName: 'Ajudante da Entrega',
    reportsShortage: false,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: 'limited',
    viewsReports: false,
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Acesso operacional minimo.'
  },
  {
    roleKey: 'gerente_deposito',
    roleName: 'Gerente do Deposito',
    reportsShortage: true,
    validatesShortage: true,
    requestsQuotes: true,
    respondsToQuotes: false,
    comparesQuotes: true,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: true,
    viewsReports: true,
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Papel chave para validar faltas do estoque.'
  },
  {
    roleKey: 'ajudante_deposito',
    roleName: 'Ajudante do Deposito',
    reportsShortage: true,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: false,
    viewsReports: false,
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Reporta falta, mas nao decide compra.'
  },
  {
    roleKey: 'contador',
    roleName: 'Contador',
    reportsShortage: false,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: false,
    viewsReports: true,
    viewsAuditTrail: true,
    managesUsersAndRoles: false,
    accessesDatabase: 'future_only',
    accessesFinancialSystems: 'future_only',
    notes: 'Acompanha documento e trilha contabil, sem operar compra.'
  },
  {
    roleKey: 'comprador',
    roleName: 'Comprador',
    reportsShortage: false,
    validatesShortage: false,
    requestsQuotes: true,
    respondsToQuotes: false,
    comparesQuotes: true,
    approvesPurchase: false,
    executesPurchase: true,
    receivesOperationalAlerts: true,
    viewsReports: true,
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Executa a compra depois da aprovacao prevista na politica.'
  },
  {
    roleKey: 'fornecedor',
    roleName: 'Fornecedor',
    reportsShortage: false,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: true,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: false,
    viewsReports: false,
    viewsAuditTrail: false,
    managesUsersAndRoles: false,
    accessesDatabase: 'blocked',
    accessesFinancialSystems: 'blocked',
    notes: 'Papel externo que responde cotacao, prazo e disponibilidade.'
  },
  {
    roleKey: 'financeiro',
    roleName: 'Financeiro',
    reportsShortage: false,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: true,
    viewsReports: true,
    viewsAuditTrail: true,
    managesUsersAndRoles: false,
    accessesDatabase: 'future_only',
    accessesFinancialSystems: 'future_only',
    notes: 'Acompanha condicoes de pagamento, sem banco liberado por padrao.'
  },
  {
    roleKey: 'auditor_interno',
    roleName: 'Auditor Interno',
    reportsShortage: false,
    validatesShortage: false,
    requestsQuotes: false,
    respondsToQuotes: false,
    comparesQuotes: false,
    approvesPurchase: false,
    executesPurchase: false,
    receivesOperationalAlerts: false,
    viewsReports: true,
    viewsAuditTrail: true,
    managesUsersAndRoles: false,
    accessesDatabase: 'future_only',
    accessesFinancialSystems: 'blocked',
    notes: 'Revisa governanca e aderencia ao processo.'
  }
];

function seedAccessMatrix() {
  saveAccessMatrix(DEFAULT_ACCESS_MATRIX);
  return DEFAULT_ACCESS_MATRIX;
}

function ensureAccessMatrix() {
  const matrix = getAccessMatrix();
  if (matrix.length) {
    return matrix;
  }
  return seedAccessMatrix();
}

module.exports = {
  DEFAULT_ACCESS_MATRIX,
  seedAccessMatrix,
  ensureAccessMatrix
};
